[package]
name = "htmxapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
actix-files = "0.6.5"
shuttle-actix-web = "0.45.0"
shuttle-runtime = "0.45.0"
tokio = "1.37.0"
serde_derive = "1.0.202"
serde = "1.0.202"
tera = "1"
